baseURL                = "https://chrisprijic.com/"
languageCode           = "en-us"
title                  = "Chris Prijic"
theme                  = "etch"
enableInlineShortcodes = true
pygmentsCodeFences     = true
pygmentsUseClasses     = true

[params]
  description      = "Chris Prijic's personal website."
  copyright        = "© 2022-present Chris Prijic (unless otherwise noted). Views are my own and do not necessarily reflect those of my employer."
  dark             = "auto"
  highlight        = true
  google_analytics = "UA-33625943-1"

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "posts"
    title      = "posts"
    url        = "/"
    weight     = 10

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true